#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/RolesAdmin/Details.cshtml")]
    public partial class _Views_RolesAdmin_Details_cshtml : System.Web.Mvc.WebViewPage<Exercicio03Modularizacao.Domain.Models.Grupo>
    {
        public _Views_RolesAdmin_Details_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\RolesAdmin\Details.cshtml"
  
    ViewBag.Title = "Details";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Details.</h2>\r\n\r\n<div>\r\n    <h4>Roles.</h4>\r\n    <hr />\r\n    <dl");

WriteLiteral(" class=\"dl-horizontal\"");

WriteLiteral(">\r\n        <dt>\r\n");

WriteLiteral("            ");

            
            #line 14 "..\..\Views\RolesAdmin\Details.cshtml"
       Write(Html.DisplayNameFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dt>\r\n        <dd>\r\n");

WriteLiteral("            ");

            
            #line 17 "..\..\Views\RolesAdmin\Details.cshtml"
       Write(Html.DisplayFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </dd>\r\n    </dl>\r\n</div>\r\n<h4>List of users in this role</h4>\r\n");

            
            #line 22 "..\..\Views\RolesAdmin\Details.cshtml"
 if (ViewBag.UserCount == 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <hr />\r\n");

WriteLiteral("    <p>No users found in this role.</p>\r\n");

            
            #line 26 "..\..\Views\RolesAdmin\Details.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n\r\n");

            
            #line 30 "..\..\Views\RolesAdmin\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\RolesAdmin\Details.cshtml"
     foreach (var item in ViewBag.Users)
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 34 "..\..\Views\RolesAdmin\Details.cshtml"
           Write(item.UserName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n");

            
            #line 37 "..\..\Views\RolesAdmin\Details.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n<p>\r\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Views\RolesAdmin\Details.cshtml"
Write(Html.ActionLink("Edit", "Edit", new { id = Model.Id }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("    ");

            
            #line 41 "..\..\Views\RolesAdmin\Details.cshtml"
Write(Html.ActionLink("Back to List", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
