// <auto-generated />
namespace GaveteiroLanches.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MovimentacaoValorTotal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovimentacaoValorTotal));
        
        string IMigrationMetadata.Id
        {
            get { return "201606291442010_MovimentacaoValorTotal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
